### ISSUE TITLE
Fails to install for me also

### ISSUE THREAD

**Issue by Nealix58** [easybotics/node-red-contrib-easybotics-ina219#11]
I just did a fresh install of the latest Raspberry Pi OS, and installed node, npm,  and node red using;
#  bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)

Next, when I cd into /home/pi/.node-red/ and try the command;

$ npm install node-red-contrib-easybotics-ina219-sensor

It fails to install.   The final end of many builds pages says;

/home/pi/.cache/node-gyp/12.20.0/include/node/v8.h:2709:40: note:   candidate expects 1 argument, 0 provided
make: *** [i2c.target.mk:111: Release/obj.target/i2c/src/i2c.o] Error 1
make: Leaving directory '/home/pi/.node-red/node_modules/i2c-bus/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.79-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/i2c-bus
gyp ERR! node -v v12.20.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! i2c-bus@1.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the i2c-bus@1.2.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-01-03T05_36_10_677Z-debug.log

**Comment by ryanmich251** [comment]
This should be fixed in the latest version (0.7.6). Feel free to reopen if you still have the issue after updating.
