### ISSUE TITLE
This node ONLY installs with node.js version 10.x and under.

### ISSUE THREAD

**Issue by Nealix58** [easybotics/node-red-contrib-easybotics-ina219#12]
This node WILL NOT install if your system is using Node.js v12.x or higher.
So if you did a fresh install of a raspberry pi OS in 2020 or later, you will need to roll back
the Node.js portion to 10.x      This can be done as follows:

Thanks to a post by Colin in Feb 2020:
First stop node-red and uninstall nodejs using
    $ sudo apt remove nodejs

Then install version 10 using the instructions in this post 13, replacing the 6 in the command with 10, 
For example:
     $ curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
Follow the instructions at the end of the above command/ install.

Then you have to re-install node-red (in order to rebuild bits of it for nodejs 10) using
     $ sudo npm install -g node-red --unsafe-perm

Finally you have to rebuild all your locally installed nodes using
      $ cd .node-red
      $ npm rebuild
Then you should be able to restart node-red.

GOOD TO GO.   The above only takes a few moments, and after that, you can install this INA219 node.

Neal

**Comment by ryanmich251** [comment]
This should be fixed in the latest version (0.7.6). Feel free to reopen if you still have the issue after updating.
