### ISSUE TITLE
flows.nodered.org (and Palette) still redirects to 0.7.5

### ISSUE THREAD

**Issue by charliejgallo** [easybotics/node-red-contrib-easybotics-ina219#14]
seems like the 0.7.6 update did not "hit" in the flow manager in Node-red and the flows page...

<img width="427" alt="Captura de Pantalla 2021-02-02 a la(s) 22 34 02" src="https://user-images.githubusercontent.com/3107041/106685331-f12a7480-65a6-11eb-969b-ccb0599ea048.png">

here they recommend something to force refresh the version in flow.nodered.org if this automatic update does not happen..., 

https://discourse.nodered.org/t/node-not-updated-in-palette-manager/10354

**Comment by ryanmich251** [comment]
Thanks for pointing that out, just updated it on flows.nodered.org, it should show up as version 0.7.6 now.

**Comment by charliejgallo** [comment]
Thanks!! installed in a fresh Pi4 with a buster image, everything OK!

<img width="182" alt="Captura de Pantalla 2021-02-02 a la(s) 23 58 41" src="https://user-images.githubusercontent.com/3107041/106691642-9eef5080-65b2-11eb-83d7-8d818299d015.png">
