### ISSUE TITLE
"Error: EMFILE: too many open files, open '/dev/i2c-1'"

### ISSUE THREAD

**Issue by Noodleyman** [easybotics/node-red-contrib-easybotics-ina219#2]
I left a test flow running all night, and this morning noted the following error from the INA219 node.

It is configured to poll every 500ms.

the failure killed the flow entirely.

update:
This also happens if you leave it running on a much longer frequency. for example once every 5 seconds. the issue happens, but takes longer to happen. When it fails, it crashes node-red and kills all flows.

I've had to stop using the node for the time being until this particular issue has a work around or fix.

**Comment by keptan** [comment]
okay /dev/i2c is being opened over and over by inaInit without being closed
easiest fix is probably patching the underlying ina library

**Comment by Noodleyman** [comment]
I'll be happy to test out any code changes, or updates. just let me know the steps you want validated. :)

**Comment by keptan** [comment]
https://github.com/easybotics/node-red-contrib-easybotics-ina219/commit/c137a641790527a0247d97b404b23ae91f9d9bc7

should clear up this issue, hope to hear from you if it worked or not

**Comment by Noodleyman** [comment]
I will set it back up and leave it running for a while to confirm. thank you :)

**Comment by Noodleyman** [comment]
Confirmed fixed.

Before the fix:
`cat /proc/sys/fs/file-nr`

the output would keep increasing until we hit the limit.

after the fix:
the output holds steady and works correctly

I think this change is good to go :)

Thank you!
