### ISSUE TITLE
INA219 node outputs two readings per output instead of one

### ISSUE THREAD

**Issue by Noodleyman** [easybotics/node-red-contrib-easybotics-ina219#3]
Testing for a flow where all I require is the current, however each time the lower output sends data, it sends two readings back to back instead of a single one.

Note, the two readings are not duplicates (in some cases) as the values can vary slightly. there are two readings instead of one being taken and sent within milliseconds of each other.

Set to output the mA every 5 seconds, debug direct from the mA output:
![image](https://user-images.githubusercontent.com/10614018/58782074-717c2380-85d5-11e9-8932-387ff0190f93.png)

**Comment by Noodleyman** [comment]
This fixed it for my application...

```
                node.vOutput = function (voltage)
                {
                        v = voltage
                        if(v == undefined || a == undefined) return

                        const msg0 = {payload: v, topic: 'voltage'}
                        //const msg1 = {payload: a, topic: 'miliamps'}
                        const msg1 = null
                        node.send([msg0, msg1])
                }


                node.aOutput = function (amps)
                {
                        a = amps
                        if(v == undefined || a == undefined) return

                        //const msg0 = {payload: v, topic: 'voltage'}
                        msg0 = null
                        const msg1 = {payload: a, topic: 'miliamps'}
                        node.send([msg0, msg1])
                }

```

**Comment by keptan** [comment]
Yeah you're on the right track, might use your patch here.

**Comment by keptan** [comment]
https://github.com/easybotics/node-red-contrib-easybotics-ina219/commit/fa27507f45a2c9cc6e19dfd8b63776c88bac94ac

fixed this bug
