### ISSUE TITLE
does seem to install, but then errors appear

### ISSUE THREAD

**Issue by girzol** [easybotics/node-red-contrib-easybotics-ina219#7]
On RPi4, with Raspbian, with Node-red 1.0.3, Node.js 10.15.2,  I install this node, seem to go OK, but when node-red restarted, an error pops up:
    Error: Cannot find module 'ina219' (line:1),

I'm so new, would appreciate any help.

**Comment by keptan** [comment]
This is a dependency issue that I'll get onto now

**Comment by keptan** [comment]
This should be sorted now, try and reinstall it
https://github.com/easybotics/node-red-contrib-easybotics-ina219/commit/ec8a58c5615707a3689352930f2a34e7c15329f2
