### ISSUE TITLE
Multiple nodes

### ISSUE THREAD

**Issue by mugginsjm** [easybotics/node-red-contrib-easybotics-ina219#8]
Hi I am trying to add 4 nodes to monitor 4 different voltage points. I can make 2 with different addresses but when I add a third with a different address it modifies the address of one of the existing two to mimic itself.

**Comment by Jamos1988** [comment]
Did you come accross issues with different readings when using multiple nodes at the same time? I use two at the moment, when using two of them I get weird readings. When I deactivate one of them, readings are fine.
